# Analyse textuelle des abstracts par STM

```{r tib_textes}
tib_doc_ABW=readRDS("data/tib_doc_ABW.RDS")
  tib_sparse_ABW=tib_doc_ABW %>% 
    group_by(ABW) %>% # compte pour chaque mot...
    mutate(n=n()) %>% # ...son nombre d'occurrences puis
    filter(n>10) %>%  # retire ceux représentés moins de 20 fois dans le corpus
    ungroup() %>% 
    cast_sparse(row=id_doc, column=ABW, value=n)
```

```{r stm}
library(stm)
if(!file.exists("data/data_trans/topic_model.RDS")){
  set.seed(123)
  topic_model<-stm(tib_sparse,K=8, verbose=FALSE)
  saveRDS(topic_model,"data/data_trans/topic_model.RDS")
}
topic_model=readRDS("data/data_trans/topic_model.RDS")
```

## Explore thématiques

```{r thematiques}
thematiques=tidytext::tidy(topic_model, matrix="beta") %>% 
  group_by(topic) %>% 
  slice_max(beta,n=20) %>%  
  mutate(rank=row_number()) %>% 
  arrange(topic,desc(beta)) %>% 
  ungroup()
```

```{r plot_thematiques, fig.width=8, fig.height=8}
ggplot(thematiques  %>%
         mutate(topic=as.factor(topic)) %>%
         mutate(term=tidytext::reorder_within(term,by=beta,within=topic)),
       aes(x=beta,y=term, fill=topic))+
  geom_bar(stat="identity")+
    facet_wrap(facets=vars(topic), scales="free")+
    theme(legend.position="none")+
  tidytext::scale_y_reordered()
```

```{r thematiques_resumees}
thematiques=thematiques %>% 
  group_by(topic) %>% 
  nest()%>%  
  summarise(topic_terms=map(data, ~paste(.$term,collapse=", "))) %>% 
  unnest(cols=c(topic_terms)) %>% 
  mutate(topic_short=case_when(topic==1~"hydrologie",
                               topic==2~"transport sédimentaire",
                               topic==3~"modélisation",
                               topic==4~"écologie",
                               topic==5~"biochimie",
                               topic==6~"quantification",
                               topic==7~"changements,risques",
                               topic==8~"étude régionale"))
```

```{r tib_meta_thematiques}

tib_gamma <- tidy(topic_model, matrix = "gamma") %>% 
  arrange(document,desc(gamma))

tib_doc_th=tib_doc_light  %>%
  mutate(document=1:n()) %>% 
  left_join(tib_gamma,by="document") %>% 
  left_join(thematiques,by="topic") 


ggplot(tib_doc_th%>% 
         group_by(PY,topic,topic_short) %>% 
         summarise(sgamma=sum(gamma),
                   n=n()) %>% 
         ungroup() %>% 
         mutate(sgamma=sgamma/n) %>% 
         na.omit(),
       aes(x=PY,y=sgamma,col=topic_short))+
  geom_smooth()
```

```{r thematiques_par_auteur}
tib_auteur_th=tib_auteur %>% 
  left_join(tib_doc_th %>% select(id_doc,topic,gamma,topic_terms,topic_short),
            by="id_doc") %>% 
  group_by(AU) %>% 
  mutate(ndoc=n()) %>%
  ungroup() %>% 
  group_by(AU,topic,topic_short) %>% 
  summarise(s=sum(gamma),
            ndoc=unique(ndoc)) %>% 
  mutate(s=s/ndoc) %>% 
  arrange(desc(ndoc)) %>% 
  ungroup() %>% 
  na.omit()
top_auteurs=tib_auteur_th %>% group_by(AU) %>% summarise(n=unique(ndoc)) %>% top_n(10) %>% pull(AU)
ggplot(tib_auteur_th %>% filter(AU %in% top_auteurs),
       aes(x=topic_short,y=s,fill=factor(topic_short)))+
  geom_col()+
  facet_wrap(facets=vars(AU))+
  coord_flip()
```
